In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("../data/raw/02_nav_history.csv")

df.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [4]:
print("Shape:", df.shape)

Shape: (46000, 3)

In [5]:
print(df.isnull().sum())

amfi_code    0
date         0
nav          0
dtype: int64

In [6]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [7]:
df["date"] = pd.to_datetime(
    df["date"],
    format="%Y-%m-%d"
)

print(df.dtypes)

amfi_code             int64
date         datetime64[us]
nav                 float64
dtype: object

In [8]:
df = df.sort_values(
    by=["amfi_code", "date"]
).reset_index(drop=True)

df.head()

   amfi_code       date       nav
0     100016 2022-01-03  520.4608
1     100016 2022-01-04  515.0971
2     100016 2022-01-05  521.7239
3     100016 2022-01-06  515.7880
4     100016 2022-01-07  515.1639

In [9]:
df["nav"] = df.groupby("amfi_code")["nav"].ffill()

In [10]:
invalid_nav = df[df["nav"] <= 0]

print("Invalid NAV values:", len(invalid_nav))

Invalid NAV values: 0

In [12]:
os.makedirs("../data/cleaned", exist_ok=True)

df.to_csv("../data/cleaned/clean_nav.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [13]:
clean_df = pd.read_csv("../data/cleaned/clean_nav.csv")

print(clean_df.head())
print("Shape:", clean_df.shape)

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639
Shape: (46000, 3)